const group = (groupName, properties) => ({
  groupName,
  emptyLineBefore: 'never',
  noEmptyLineBetween: true,
  properties,
});

module.exports = {
  plugins: ['stylelint-order'],
  overrides: [
    {
      files: ['**/*.vue'],
      customSyntax: 'postcss-html',
    },
    {
      files: ['**/*.scss'],
      customSyntax: 'postcss-scss',
    },
  ],
  rules: {
    'order/properties-order': [
      [
        group('位置 / 布局', [
          'position',
          'top',
          'right',
          'bottom',
          'left',
          'inset',
          'inset-block',
          'inset-inline',
          'z-index',
          'display',
          'visibility',
          'flex',
          'flex-grow',
          'flex-shrink',
          'flex-basis',
          'flex-flow',
          'flex-direction',
          'flex-wrap',
          'justify-content',
          'justify-items',
          'justify-self',
          'align-content',
          'align-items',
          'align-self',
          'place-content',
          'place-items',
          'place-self',
          'order',
          'gap',
          'row-gap',
          'column-gap',
          'grid',
          'grid-template',
          'grid-template-areas',
          'grid-template-rows',
          'grid-template-columns',
          'grid-auto-flow',
          'grid-auto-rows',
          'grid-auto-columns',
          'grid-area',
          'grid-row',
          'grid-column',
          'float',
          'clear',
          'overflow',
          'overflow-x',
          'overflow-y',
          'overflow-wrap',
          'overscroll-behavior',
          'clip',
          'clip-path',
        ]),
        group('尺寸', [
          'box-sizing',
          'width',
          'height',
          'min-width',
          'max-width',
          'min-height',
          'max-height',
          'aspect-ratio',
          'resize',
        ]),
        group('外边距', [
          'margin',
          'margin-top',
          'margin-right',
          'margin-bottom',
          'margin-left',
          'margin-block',
          'margin-block-start',
          'margin-block-end',
          'margin-inline',
          'margin-inline-start',
          'margin-inline-end',
        ]),
        group('内边距', [
          'padding',
          'padding-top',
          'padding-right',
          'padding-bottom',
          'padding-left',
          'padding-block',
          'padding-block-start',
          'padding-block-end',
          'padding-inline',
          'padding-inline-start',
          'padding-inline-end',
        ]),
        group('边框', [
          'border',
          'border-width',
          'border-style',
          'border-color',
          'border-top',
          'border-right',
          'border-bottom',
          'border-left',
          'border-block',
          'border-inline',
          'border-radius',
          'outline',
          'outline-width',
          'outline-style',
          'outline-color',
          'outline-offset',
        ]),
        group('颜色', ['color', 'accent-color', 'caret-color', 'fill', 'stroke']),
        group('背景', [
          'background',
          'background-color',
          'background-image',
          'background-repeat',
          'background-attachment',
          'background-size',
          'background-position',
          'background-origin',
          'background-clip',
          'background-blend-mode',
        ]),
        group('文字', [
          'font',
          'font-size',
          'font-weight',
          'font-style',
          'font-variant',
          'font-family',
          'font-stretch',
          'line-height',
          'letter-spacing',
          'word-spacing',
          'text-align',
          'text-align-last',
          'text-indent',
          'text-transform',
          'text-decoration',
          'text-overflow',
          'text-rendering',
          'vertical-align',
          'white-space',
          'word-break',
          'hyphens',
        ]),
        group('列表 / 表格', [
          'list-style',
          'list-style-type',
          'list-style-position',
          'list-style-image',
          'table-layout',
          'border-collapse',
          'border-spacing',
          'caption-side',
          'empty-cells',
        ]),
        group('阴影', ['box-shadow', 'text-shadow', 'filter', 'backdrop-filter']),
        group('透明度', ['opacity', 'mix-blend-mode', 'isolation']),
        group('变换', ['transform', 'transform-origin', 'transform-style', 'perspective']),
        group('过渡动画', [
          'transition',
          'transition-property',
          'transition-duration',
          'transition-timing-function',
          'transition-delay',
          'animation',
          'animation-name',
          'animation-duration',
          'animation-timing-function',
          'animation-delay',
          'animation-iteration-count',
          'animation-direction',
          'animation-fill-mode',
          'animation-play-state',
        ]),
        group('其他', [
          'appearance',
          'content',
          'quotes',
          'counter-reset',
          'counter-increment',
          'cursor',
          'pointer-events',
          'touch-action',
          'user-select',
          'scroll-behavior',
          'scroll-margin',
          'scroll-padding',
          'object-fit',
          'object-position',
        ]),
      ],
      {
        unspecified: 'bottomAlphabetical',
      },
    ],
  },
};
